spring.application.name=cqrs-training
spring.datasource.url=jdbc:h2:mem:cqrs-training-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Spring Cloud Stream ? egyetlen events topic a microservice-hez
spring.cloud.function.definition=enrollmentEventsConsumer

spring.cloud.stream.bindings.events-out-0.destination=enrollment.events
spring.cloud.stream.bindings.events-out-0.content-type=application/json

spring.cloud.stream.bindings.enrollmentEventsConsumer-in-0.destination=enrollment.events
spring.cloud.stream.bindings.enrollmentEventsConsumer-in-0.group=cqrs-training-read-model
spring.cloud.stream.bindings.enrollmentEventsConsumer-in-0.content-type=application/json

# Particionálás: courseId alapján ? így egy kurzus eseményei mindig sorrendben érkeznek
spring.cloud.stream.bindings.events-out-0.producer.partition-key-expression=headers['partitionKey']
spring.cloud.stream.bindings.events-out-0.producer.partition-count=1
